FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN pip install --no-cache-dir uv && uv pip install --system .

COPY . .

CMD ["celery", "-A", "src.tasks.celery_app:celery_app", "worker", "--loglevel=info", "-Q", "celery"]